name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker
      run: docker login -u lsy2006 -p QaZ963963#
    - name: Docker Compose Build, Up & Push
      run: |
        docker-compose build
        docker-compose up
        docker-compose push
  
