# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Run Backend Tests
      run: npm run backend-test
    - name: Debug Public Folder
      run: ls -la public
    - name: Instrument Frontend Code
      run: |
        mkdir -p instrumented
        cp -R public/* instrumented/
        npx nyc instrument instrumented instrumented
    - name: Run Frontend Tests (Chrome)
      run: npm run frontend-test:chrome
    - name: Run Frontend Tests (Cypress)
      run: npm run frontend-test:cypress
    - name: Run Frontend Tests (Firefox)
      run: npm run frontend-test:firefox
