name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        browser: [chrome, firefox, electron]  # Browsers for testing

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Build the application (if applicable)
      - run: npm run build --if-present

      # Install Cypress
      - name: Install Cypress
        run: npm install cypress

      # Run Cypress tests
      - name: Run Cypress tests in ${{ matrix.browser }}
        run: |
          npx cypress run --browser ${{ matrix.browser }}

      # Ensure Docker Compose is installed
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      # Log in to Docker Hub
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build, run, and push Docker image
      - name: Docker Compose Build, Up & Push
        run: |
          docker-compose build
          docker-compose up -d  # Use -d for detached mode
          docker-compose push
          
      - name: Azure CLI Download
        run: az aks install-cli
