# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    - name: Run Backend Tests
      run: npm run backend-test

    - name: Run Frontend Tests (Chrome)
      run: |
        mkdir -p instrumented-chrome
        cp -R public/* instrumented-chrome/
        npx nyc instrument public instrumented-chrome --output instrumented-chrome
        npm run frontend-test:chrome
        
    - name: Wait Between Runs
      run: sleep 10
    - name: Clean Temporary Files
      run: |
        rm -rf .nyc_output coverage cypress/screenshots cypress/videos

    - name: Run Frontend Tests (Cypress)
      run: |
        mkdir -p instrumented-cypress
        cp -R public/* instrumented-cypress/
        npx nyc instrument public instrumented-cypress --output instrumented-cypress
        npm run frontend-test:cypress

    - name: Wait Between Runs
      run: sleep 10
    - name: Clean Temporary Files
      run: |
        rm -rf .nyc_output coverage cypress/screenshots cypress/videos
        
    - name: Run Frontend Tests (Firefox)
      run: |
        mkdir -p instrumented-firefox
        cp -R public/* instrumented-firefox/
        npx nyc instrument public instrumented-firefox --output instrumented-firefox
        npm run frontend-test:firefox

