name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        browser: [chrome, firefox, electron]  # Browsers for testing

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies
      - run: npm ci

      # Build the application (if applicable)
      - run: npm run build --if-present

      # Install Cypress
      - name: Install Cypress
        run: npm install cypress

      # Run Cypress tests
      - name: Run Cypress tests in ${{ matrix.browser }}
        run: |
          npx cypress run --browser ${{ matrix.browser }}

      # Ensure Docker Compose is installed
      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      # Log in to Docker Hub
      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build, run, and push Docker image
      - name: Docker Compose Build, Up & Push
        run: |
          docker-compose build
          docker-compose up -d  # Use -d for detached mode
          docker-compose push
          
      - name: Azure CLI Download
        run: az aks install-cli

      - name: Azure Login
        run: az login --service-principal -u "c119e108-39a8-492d-a8e2-8643490424be" -p "doc8Q~F4ID~SkPiK4BZHx73A1zum_EzSL6l_mbHT" --tenant "25a99bf0-8e72-472a-ae50-adfbdf0df6f1"

      - name: Azure AKS Creation
        run: az aks show --resource-group rmsDevOpsGroup --name rmsAKSCluster -o json >nul 2>nul || az aks create --resource-group rmsDevOpsGroup--name rmsAKSCluster --node-count 1 --generate-ssh-keys 2>&1

      - name: Azure Get Credential
        run: az aks get-credentials --resource-group "rmsDevOpsGroup" --name "rmsAKSCluster" --overwrite-existing --subscription "817d3e18-4278-4b40-9af7-3ad7e73f6664"

      - name: K8s Creation
        run: |
          kubectl apply -f rms-deployment.yaml
          kubectl apply -f rms-service.yaml
          kubectl rollout history deployment/rms-deployment
          kubectl get pods
          kubectl get services
      
